### ISSUE TITLE
（1）开始访问获取客户订阅日期详细信息：GetCustSubscribeDateDetail 401 访问异常,继续访问

### ISSUE THREAD

**Issue by cheshennull** [LiCain/JiuJia#1]
您好，程序报错。

（1）开始访问获取客户订阅日期详细信息：GetCustSubscribeDateDetail
401
访问异常,继续访问

**Comment by LiCain** [comment]
您好，今天看到，刚刚更新了，您可以去看下，需要您配置一下你的 cookies,不然会出现401 访问
如果当前抢的九价没开放是无法获得mxid ,获取不了就无法下一步，这里我提供的一个思路，祝您成功

**Comment by janyyy** [comment]
简单写个操作手册把
