### ISSUE TITLE
大佬，mxid怎么搞定的

### ISSUE THREAD

**Issue by fengshilin** [LiCain/JiuJia#6]
现在这个code_json_dict = code.json()会报错，说解析不了，看这个GetCustSubscribeDateDetail的结果应该是mxid,但是是一串字符串，跟fildder获取的mxid不一样。字符串像这样的，这应该怎么办诶
848E1DFB04FE20D0557C31C10670F5DD7EB3507BAA3FAAD31AB0C3BC3622EC7D4A605977D52AB5E7B53E26EF56C0138B63F90C7E2A798DCC3B07FFABD7F50AFE3F8912157A2C390DDCF253AB10DEEA3936C83B9EB5C94A947A7135DE6FA268F564CF9DB4510C0972D86082A4737CAF521172044718A4259B35738FFE51EA84C098AC91647DD1DFA180DA01CC8F66EEDADF6D0BC2DCDE115DCF61695F7F127A06205E43E73F506B41A7D82CA9E704B114C2738C43684AA43420B3CDADD24BF56E5807CD78B80B24A7B41B2CC28760E9502DD4023CFC260E8F19AF85F2FA5CD30A0C5BBD8B4EE468F977E22FE33631D6CA55F51784816C48BF8148DB9A13A0DD3CB28F1EFEE56DF776F3A0A7C0902CA9DD5E02C3B5EB7C26A7BA3F1F3B374E3550ABF85FE79A03A4B5242BEEFF65765A19

**Comment by CalvinY058** [comment]
老哥，整出来了不，咋加解密的

**Comment by CalvinY058** [comment]
> > 这个应该是新增的加密，只能反编译小程序去js里面看解密方法了
> 
> 我看不懂js，大概定位在这里，您知道这个代码是怎么加密的吗？ ![图片](https://user-images.githubusercontent.com/51773634/136756257-86e82da2-31ff-48ba-afc2-49c4765aa1d7.png) ![图片](https://user-images.githubusercontent.com/51773634/136756470-fc5228de-f91c-4123-bd35-5e12d25227e2.png)
老哥，整出来了不，咋加解密的

**Comment by image2021** [comment]
js小白，今天看了下代码，感觉是不是已经没办法破了。。。
![image](https://user-images.githubusercontent.com/76997679/141279279-92bb8896-2a21-4a52-955d-495a709efec0.png)
![image](https://user-images.githubusercontent.com/76997679/141279363-ba6ea4fd-cf54-402f-948d-8d297e00c033.png)
![image](https://user-images.githubusercontent.com/76997679/141279425-ecb2ad57-bf01-42e1-a4bd-d47e5f3f5b16.png)

**Comment by cjpcool** [comment]
> js小白，今天看了下代码，感觉是不是已经没办法破了。。。 ![image](https://user-images.githubusercontent.com/76997679/141279279-92bb8896-2a21-4a52-955d-495a709efec0.png) ![image](https://user-images.githubusercontent.com/76997679/141279363-ba6ea4fd-cf54-402f-948d-8d297e00c033.png) ![image](https://user-images.githubusercontent.com/76997679/141279425-ecb2ad57-bf01-42e1-a4bd-d47e5f3f5b16.png)

这个c.signature是不是 保存的 set_cookcies 里面的那个 session_id 啊。。。有人搞定了吗

**Comment by kikitte** [comment]
目前我的思路是通过Xposed劫持微信小程序的jsruntime和webview，通过注入代码到小程序实现预约。目前已经实现webview代码注入了，上面提到的的mxid很容易获取。没有按照这个项目的脚本继续实现是因为当前的代码貌似没有实现处理验证码的逻辑，应该不是那么好过。所以我的思路是把抢购代码直接注入到小程序WebView上去让这个抢购过程自动化，最后一步验证码就由人工完成。但目前在触发小程序元素的点击事件上碰到了问题。。
![image](https://user-images.githubusercontent.com/23274684/142762711-7e7551c1-9505-41f2-9d16-88c6f0edc0e6.png)

**Comment by rambodoctor** [comment]
> 目前我的思路是通过Xposed劫持微信小程序的jsruntime和webview，通过注入代码到小程序实现预约。目前已经实现webview代码注入了，上面提到的的mxid很容易获取。没有按照这个项目的脚本继续实现是因为当前的代码貌似没有实现处理验证码的逻辑，应该不是那么好过。所以我的思路是把抢购代码直接注入到小程序WebView上去让这个抢购过程自动化，最后一步验证码就由人工完成。但目前在触发小程序元素的点击事件上碰到了问题。。 ![image](https://user-images.githubusercontent.com/23274684/142762711-7e7551c1-9505-41f2-9d16-88c6f0edc0e6.png)
抢购自动化我已经用JavaScript实现了 但是速度不行，而且受到小程序过渡动画的影响  大大加长了预约时间， 但我这里疫苗预约的时间通常只有不到5秒   所以模拟操作是没有前途的，需要用p之前的方法 直接使用程序向服务器发包，才可能抢到

**Comment by kikitte** [comment]
> > 目前我的思路是通过Xposed劫持微信小程序的jsruntime和webview，通过注入代码到小程序实现预约。目前已经实现webview代码注入了，上面提到的的mxid很容易获取。没有按照这个项目的脚本继续实现是因为当前的代码貌似没有实现处理验证码的逻辑，应该不是那么好过。所以我的思路是把抢购代码直接注入到小程序WebView上去让这个抢购过程自动化，最后一步验证码就由人工完成。但目前在触发小程序元素的点击事件上碰到了问题。。 ![image](https://user-images.githubusercontent.com/23274684/142762711-7e7551c1-9505-41f2-9d16-88c6f0edc0e6.png)
> > 抢购自动化我已经用JavaScript实现了 但是速度不行，而且受到小程序过渡动画的影响  大大加长了预约时间， 但我这里疫苗预约的时间通常只有不到5秒   所以模拟操作是没有前途的，需要用p之前的方法 直接使用程序向服务器发包，才可能抢到

可以啊很厉害，听你这么一说我也感觉是有这个问题，但是纯粹使用脚本抢购要解决验证码这个问题，对我而言目前感觉无能为力。这样说来反而本issue里面提到的mxid算是好解决的，/笑。看了下一些仓库，比如这个https://github.com/yuemiao-web/yuemiao_backend/issues/1， 验证码校验也是没有很完善。

**Comment by ioppio** [comment]
MXID  。纯算法 需要加V：GTA377

**Comment by siniankxq** [comment]
> 程序过渡动画的影响 大大加长了预约时间， 但我这里疫苗预约的时间通常只有不到5秒 所以模拟操作是没有前途的，需要用p之前的方法 直接使用程序向服务器发包，才可能抢到

好像需要hook微信 获取到wx.getUserInfo 返回的signature, 就可以解密了

**Comment by shenzhenjinma** [comment]
要不要组个群讨论？

**Comment by liuzixuan1** [comment]
> 

大佬，目前知喵易约不需要  验证码了啊

**Comment by Mcler520** [comment]
> 

能提交下注入的脚本吗？

**Comment by itianfen** [comment]
> > 程序过渡动画的影响 大大加长了预约时间， 但我这里疫苗预约的时间通常只有不到5秒 所以模拟操作是没有前途的，需要用p之前的方法 直接使用程序向服务器发包，才可能抢到
> 
> 好像需要hook微信 获取到wx.getUserInfo 返回的signature, 就可以解密了

有具体的操作方法吗 卡在获取到wx.getUserInfo 返回的signature了 要秃了

**Comment by YingSheep2q** [comment]
> > > 目前我的思路是通过提出了劫持微信小程序的js运行时和webview，通过注入代码到小程序实现预约。目前已经实现webview代码注入了，上面提到的的mxid很容易获取.没有按照这个项目的脚本继续实现是因为当前的代码貌似没有实现处理验证码的逻辑，应该不是那么好过.所以我的思路是把抢购代码直接注入到小程序WebView上去让这个抢购过程自动化，最后一步验证码就由人工完成.但目前在触发小程序元素的点击事件上碰到了问题.![image](https://user-images.githubusercontent.com/23274684/142762711-7e7551c1-9505-41f2-9d16-88c6f0edc0e6.png)抢购自动化我已经用JavaScript实现了但是速度不行，而且受到小程序过渡动画的影响大大加长了预约时间，但我这里疫苗预约的时间通常只有不到5秒所以模拟操作是没有前途的，需要用p之前的方法直接使用程序向服务器发包，才可能抢到
> 
> 可以啊很厉害，听你这么一说我也感觉是有这个问题，但是纯粹使用脚本抢购要解决验证码这个问题，对我而言目前感觉无能为力.这样说来反而本发布里面提到的mxid算是好解决的，/笑。看了下一些仓库，比如这个[Https://github.com/yuemiao-web/yuemiao_backend/issues/1，](https://github.com/yuemiao-web/yuemiao_backend/issues/1%EF%BC%8C)验证码校验也是没有很完善.

大佬 如何解密GetCustSubscribeDateDetail返回的值。。

**Comment by vbigbang** [comment]
hook微信能拿出mxid 但是如何解密GetCustSubscribeDateDetail返回的值..... 提交预约要知道时间段的吧

**Comment by teg1c** [comment]
我这边已经hook拿到signature了，但是还是解密失败了。有没有大佬一起来讨论下

**Comment by teg1c** [comment]
> hook微信能拿出mxid 但是如何解密GetCustSubscribeDateDetail返回的值..... 提交预约要知道时间段的吧

能预测到时间的。

**Comment by Halfwaygo** [comment]
> mark 现在mxid没法获取，这里用了加密

需要signture  ，需要加Q 1435131167

**Comment by vbigbang** [comment]
> > mark 现在mxid没法获取，这里用了加密
> 
> 需要signture ，需要加Q 1435131167

可以获取 另外signature hook即可

**Comment by teg1c** [comment]
hook 获取 signature 可以联系 514321066

**Comment by shenzhenjinma** [comment]
【自动回复】

    您好，这封是自动回复，我在看到您的邮件将第一时间回复，


    如有紧急问题请电话联系。


    
        注：若您收到此信息说明服务器已经接收到您的邮件

**Comment by 199457** [comment]
@kikitte 请问 mxid 如何解决的？

**Comment by BuingBuing** [comment]
> @kikitte 请问mxid 如何解决的？

wx Klover_ 收费解决 可提供租用

**Comment by 199457** [comment]
> 

已经解决了

**Comment by shidi-zai** [comment]
> @kikitte 请问 mxid 如何解决的？

接口获取密钥解密 按次收费 5元一次 +Q 939505402 包解密

**Comment by yuejinzhao** [comment]
> > > mark 现在mxid没法获取，这里用了加密
> > 
> > 
> > 需要signture ，需要加Q 1435131167
> 
> 可以获取 另外signature hook即可
是类型hook pc微信回复消息发送消息的思路吗

**Comment by yuejinzhao** [comment]
> > > mark 现在mxid没法获取，这里用了加密
> > 
> > 
> > 需要signture ，需要加Q 1435131167
> 
> 可以获取 另外signature hook即可

@vbigbang 是类似hook pc微信发送接收消息之类的思路吗
